name: Publish NPM Packages

on:
  workflow_dispatch:
  push:

jobs:
  build-and-test:
    uses: ./.github/workflows/ci.yml

  publish-platform-packages:
    name: Publish Platform Specific Packge
    runs-on: ubuntu-latest
    needs:
      - build-and-test

    strategy:
      matrix:
        target:
          - darwin-arm64
          - darwin-x64
          - linux-arm64
          - linux-x64

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          # This should always be the current NodeJS LTS release.
          node-version: 18
          registry: 'https://registry.npmjs.org'

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: libuv-monitor.${{ matrix.target }}.node
          path: npm/${{ matrix.target }}

      - name: List Packages
        run: ls -R .

      - name: Publish Platform Specific Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          cd npm/${{ matrix.target }}
          npm publish --access public

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs:
      - publish-platform-packages

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          # This should always be the current NodeJS LTS release.
          node-version: 18
          registry: 'https://registry.npmjs.org'

      - name: List Packages
        run: ls -R .

      - name: Publish Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: npm publish --access public
